<a href="https://colab.research.google.com/github/nipunikajain/DeepLearning1/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.1+cu116


### Introduction to Tensors

Creating Tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar


tensor(7)

In [4]:
scalar.ndim
## A scalar has no dimension

0

In [5]:
# Get tensor back as python int

scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                      [3,4]])

MATRIX

tensor([[7, 8],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
# Tensor

TENSOR = torch.tensor([[[1,3,4],
                       [2,5,6],
                       [3,7,8]]])

TENSOR

tensor([[[1, 3, 4],
         [2, 5, 6],
         [3, 7, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 3, 4],
        [2, 5, 6],
        [3, 7, 8]])

In [17]:
a = torch.tensor([[1],
                  [1],
                  [1],
                  [1],
                  [1]])

In [18]:
a.ndim

2

In [19]:
a.shape

torch.Size([5, 1])

In [20]:
a

tensor([[1],
        [1],
        [1],
        [1],
        [1]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`
Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html


In [21]:
### Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2605, 0.4472, 0.5788, 0.7225],
        [0.8708, 0.2408, 0.1428, 0.5920],
        [0.2529, 0.9673, 0.0996, 0.6113]])

In [22]:
# Create a random tensor with similar shape to an image tensor

ranom_image_size_tensor = torch.rand(size= (224,224,3)) # height, width, color channels ( R,G,B )

ranom_image_size_tensor.shape, ranom_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
ranom_image_size_tensor.size()

torch.Size([224, 224, 3])

### Zeros and ones

In [24]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# create a tensor of all ones

ones = torch.ones( size = (3,4) )
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [27]:
# Use torch.arange()

one_to_ten = torch.arange(start = 1,end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensors-like

ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**NOTE:** Tensor Datatypes is one of the 3 big errors u'll run into with Pytorch and DL

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in Computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [29]:
# fLOAT 32 TENSOR

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (eg: float32,float16)
                               device = None, # what device is your tensor on
                               requires_grad  = False) # whether or not to track gradients with this tensor operations

float_32_tensor 

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor  = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,4,4], dtype = torch.long)
int_32_tensor

tensor([3, 4, 4])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 36.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [35]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0161, 0.6913, 0.6692, 0.5980],
        [0.8281, 0.3127, 0.9325, 0.1455],
        [0.3409, 0.1247, 0.4000, 0.1843]])

In [36]:
# find out details about some_tensor

print(some_tensor)
print(f"Datatype of Tensor:", some_tensor.dtype)
print(f"Shape of Tensor:", some_tensor.shape)
print(f"Device of Tensor:", some_tensor.device)

tensor([[0.0161, 0.6913, 0.6692, 0.5980],
        [0.8281, 0.3127, 0.9325, 0.1455],
        [0.3409, 0.1247, 0.4000, 0.1843]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu


In [37]:
x = torch.rand([2,3],dtype= torch.float64)
x

tensor([[0.0591, 0.8897, 0.7105],
        [0.8452, 0.4879, 0.0795]], dtype=torch.float64)

In [38]:
print(x)
print(f"Datatype of Tensor:", x.dtype)
print(f"Shape of Tensor:", x.shape)
print(f"Device of Tensor:", x.device)

tensor([[0.0591, 0.8897, 0.7105],
        [0.8452, 0.4879, 0.0795]], dtype=torch.float64)
Datatype of Tensor: torch.float64
Shape of Tensor: torch.Size([2, 3])
Device of Tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication 
* Division
* Matrix multiplication

In [39]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in NN and Deep learning:
1. Element-wise multiplication
2. Matrix multiplication ( dot product )

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [42]:
# Element wise multiplication

print(tensor, "*", tensor)
print("Equals:", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in DL : Shape Errors

In [48]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])





To fix tensor shape issues we can manipulate the shape using **transpose**



In [51]:
output = torch.matmul(tensor_A, tensor_B.T)

### Finding the min, max, mean, sum ( tensor aggregation )

In [52]:
# create a tensor

x = torch.arange(0,100,10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
torch.min(x)

tensor(0)

In [54]:
# Find the max

torch.max(x)

tensor(90)

In [57]:
# Find the mean - note: torch.mean function requires tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [58]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [60]:
torch.argmax(x)

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
*  Stacking - combine multiple tensors on the top of each other, hstack and vstack
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze -  add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [75]:
# create a tensor

x = torch.arange(1.,10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [76]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# Change the view 

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
# changing z changes x ( becoz the view of a tensor shares the same memory as the original input)

z[:,0] = 5

z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other

