<a href="https://colab.research.google.com/github/nipunikajain/DeepLearning1/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.1+cu116


### Introduction to Tensors

Creating Tensors

In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0,1]

tensor([3, 6, 9])

### Random Tensors

Why random tensors?

Random tensors are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Create a randim tensor of size (3,4)


random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3882, 0.2722, 0.7420, 0.3548],
        [0.4425, 0.0102, 0.4183, 0.4545],
        [0.5940, 0.6731, 0.8572, 0.9890]])

In [16]:
random_tensor.ndim

2

In [17]:
# create a randim tensor with similar shape to an image tensor

random_image_size_tensor= torch.rand(size=(224,224,3)) # height, width, colour channels (R,G,B)

random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [18]:
mytensor = torch.rand(2,5,3)
mytensor[0]

tensor([[0.4260, 0.2016, 0.1491],
        [0.1507, 0.1790, 0.6681],
        [0.6490, 0.9323, 0.5663],
        [0.3680, 0.5560, 0.1109],
        [0.4790, 0.9924, 0.3233]])

### Zeroes and ones


In [19]:
# CREATE A TENSOR OF ALL ZEROES

zeros = torch.zeros(3,4)

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create tensors of all ones

ones = torch.ones(3,4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range()

one_to_ten = torch.arange(start = 1,end=10,step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Creating tensors like


ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes

**Note:** Tensor datatyoes is one of the 3 big errors u'll run into with PyTorch & DL:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [26]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype= None, # datatype of tensor
                               device=None, # What device is ur tensor on
                               requires_grad=False) # whether or not to track gradiet with tensor operations

float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_32_tensor.dtype

torch.float16

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor

In [38]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype= torch.int32)

int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting info from Tensors ( Tensor attributes )

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`

3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [40]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0360, 0.0598, 0.2114, 0.3122],
        [0.8562, 0.8654, 0.3247, 0.3612],
        [0.7182, 0.5914, 0.1240, 0.9854]])

In [41]:
# Find out details about some_tensor

print(some_tensor)
print(f"Datatype of Tensor:{some_tensor.dtype}")
print(f"Shape of Tensor:{some_tensor.shape}")
print(f"Device of Tensor:{some_tensor.device}")

tensor([[0.0360, 0.0598, 0.2114, 0.3122],
        [0.8562, 0.8654, 0.3247, 0.3612],
        [0.7182, 0.5914, 0.1240, 0.9854]])
Datatype of Tensor:torch.float32
Shape of Tensor:torch.Size([3, 4])
Device of Tensor:cpu


### Manipulating Tensor ( Tensor operations )

Tensor operations include:
 * Addition
 * Subtraction
 * Multiplication (element-wise)
 * Division
 * Matrix Multiplication

In [42]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply a tensor by 10

tensor * 10

tensor([10, 20, 30])

In [44]:
# Subtract 10

tensor -10

tensor([-9, -8, -7])

In [45]:
# Try out PyTorch in-built Functions

torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multiplication
2. Matrix multiplication ( dot product )

In [50]:
 # element wise multiplication

 tensor

tensor([1, 2, 3])

In [49]:
 torch.matmul(tensor,tensor)

tensor(14)