<a href="https://colab.research.google.com/github/nipunikajain/DeepLearning1/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.1+cu116


### Introduction to Tensors

Creating Tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar


tensor(7)

In [ ]:
scalar.ndim
## A scalar has no dimension

0

In [ ]:
# Get tensor back as python int

scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                      [3,4]])

MATRIX

tensor([[7, 8],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,3,4],
                       [2,5,6],
                       [3,7,8]]])

TENSOR

tensor([[[1, 3, 4],
         [2, 5, 6],
         [3, 7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 3, 4],
        [2, 5, 6],
        [3, 7, 8]])

In [ ]:
a = torch.tensor([[1],
                  [1],
                  [1],
                  [1],
                  [1]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

torch.Size([5, 1])

In [ ]:
a

tensor([[1],
        [1],
        [1],
        [1],
        [1]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`
Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
### Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7527, 0.8583, 0.3655, 0.0267],
        [0.1779, 0.4063, 0.7298, 0.9888],
        [0.5360, 0.4373, 0.1087, 0.4728]])

In [ ]:
# Create a random tensor with similar shape to an image tensor

ranom_image_size_tensor = torch.rand(size= (224,224,3)) # height, width, color channels ( R,G,B )

ranom_image_size_tensor.shape, ranom_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
ranom_image_size_tensor.size()

torch.Size([224, 224, 3])

### Zeros and ones

In [ ]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones

ones = torch.ones( size = (3,4) )
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [ ]:
# Use torch.arange()

one_to_ten = torch.arange(start = 1,end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors-like

ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**NOTE:** Tensor Datatypes is one of the 3 big errors u'll run into with Pytorch and DL

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in Computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# fLOAT 32 TENSOR

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (eg: float32,float16)
                               device = None, # what device is your tensor on
                               requires_grad  = False) # whether or not to track gradients with this tensor operations

float_32_tensor 

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor  = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,4,4], dtype = torch.long)
int_32_tensor

tensor([3, 4, 4])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 36.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [ ]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4195, 0.3505, 0.3024, 0.5296],
        [0.3461, 0.7640, 0.7317, 0.7057],
        [0.2401, 0.3536, 0.9585, 0.9125]])

In [ ]:
# find out details about some_tensor

print(some_tensor)
print(f"Datatype of Tensor:", some_tensor.dtype)
print(f"Shape of Tensor:", some_tensor.shape)
print(f"Device of Tensor:", some_tensor.device)

tensor([[0.4195, 0.3505, 0.3024, 0.5296],
        [0.3461, 0.7640, 0.7317, 0.7057],
        [0.2401, 0.3536, 0.9585, 0.9125]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu


In [ ]:
x = torch.rand([2,3],dtype= torch.float64)
x

tensor([[5.0183e-01, 5.9856e-02, 8.7523e-01],
        [7.6170e-04, 3.3248e-01, 2.9205e-01]], dtype=torch.float64)

In [ ]:
print(x)
print(f"Datatype of Tensor:", x.dtype)
print(f"Shape of Tensor:", x.shape)
print(f"Device of Tensor:", x.device)

tensor([[5.0183e-01, 5.9856e-02, 8.7523e-01],
        [7.6170e-04, 3.3248e-01, 2.9205e-01]], dtype=torch.float64)
Datatype of Tensor: torch.float64
Shape of Tensor: torch.Size([2, 3])
Device of Tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication 
* Division
* Matrix multiplication

In [ ]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in NN and Deep learning:
1. Element-wise multiplication
2. Matrix multiplication ( dot product )

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
# Element wise multiplication

print(tensor, "*", tensor)
print("Equals:", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in DL : Shape Errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])





To fix tensor shape issues we can manipulate the shape using **transpose**



In [ ]:
output = torch.matmul(tensor_A, tensor_B.T)

### Finding the min, max, mean, sum ( tensor aggregation )

In [ ]:
# create a tensor

x = torch.arange(0,100,10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
# Find the max

torch.max(x)

tensor(90)

In [ ]:
# Find the mean - note: torch.mean function requires tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
torch.argmax(x)

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
*  Stacking - combine multiple tensors on the top of each other, hstack and vstack
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze -  add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor

x = torch.arange(1.,10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view 

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x ( becoz the view of a tensor shares the same memory as the original input)

z[:,0] = 5

z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.vstack([x,x])

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.hstack([x,x])

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() - removes all single dimensions from a tensor

x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_reshaped.squeeze()

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_unsqueezed.shape


torch.Size([1, 9])

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size = (224,224,3))
# Permute the original tensor to rearrange the axis or dim order

x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_original[0,0,0] = 72828
x_original[0,0,0], x_permuted[0,0,0]

(tensor(72828.), tensor(72828.))

## Indexing ( selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
# create a tensor

x = torch.arange(1,10).reshape(1,3,3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)

x[0][0]

tensor([1, 2, 3])

In [ ]:

x[0][0][0]

tensor(1)

## Pytorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_nummpy(ndarray)`

* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [ ]:
 # Numpy array to tensor

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch, pytorch reflects numpy default datatype of float64 unless specificed otherwise


array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of array, what will this do to tensor?

array = array+1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tENDOR TO nUMpY ARRAY

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to `numpy_tensor`?

tensor = tensor +1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducbility ( trying to take random out of random )

I short how a NN learns:

` start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again .... `

To reduce the randomness in NN and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.


In [ ]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.1238, 0.2117, 0.4818, 0.1788],
        [0.5512, 0.7137, 0.4301, 0.5611],
        [0.1832, 0.5534, 0.7130, 0.5680]])
tensor([[0.2437, 0.3564, 0.7168, 0.2794],
        [0.1384, 0.1439, 0.7027, 0.8909],
        [0.4127, 0.3058, 0.2528, 0.0198]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)


random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors or PyTorch objects in GPUs and making faster computations

GPUs = faster computaiton on numbers, thanks to CUDA + NVIDIA hardware + Pytorch

### 1. Getting a GPU

1. Easiest = use Google colab GPU ( options to upgrade as well )

2. Use your own GPU = requires effort and costing of GPU

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 Pytorch + GPU drivers (CUDA) takes little bit of setting up, to do this, refer to pytorch documentation

In [ ]:
import torch

torch.cuda.is_available()

False

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cpu'

In [ ]:
# count the number of devices

torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

## Putting tensors and models on GPU
 The reason we want our tensors/models on GPU is because using a GPU is faster in computations


In [ ]:
# create a tensor (default on CPU)

tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available

tensor_on_gpur = tensor.to(device)

tensor_on_gpur.device

device(type='cpu')

### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to numpy

# To fix GPU tensor to numpy issue, we first set it to CPU

tensor_back_on_CPU = tensor_on_gpur.cpu().numpy()
tensor_back_on_CPU
# tensor_on_gpur.numpy()

array([1, 2, 3])

## Exercises and Extra-Curriculum